# Generated by Django 2.0.2 on 2018-03-01 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Linha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_atual', models.CharField(default='', max_length=256)),
                ('nome_atual', models.CharField(default='', max_length=256)),
                ('novo_nome', models.CharField(default='', max_length=256)),
                ('proposta', models.CharField(default='', max_length=256)),
            ],
        ),
    ]
